package DEMSApp;


/**
* DEMSApp/ManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CM.idl
* Sunday, March 1, 2020 8:09:59 AM EST
*/

public interface ManagerOperations 
{
  String addEvent (String eventID, String eventType, int bookingCapacity, String serv);
  String removeEvent (String eventID, String eventType, String serv);
  String listEventAvailability (String eventType, String serv);
  String bookEvent (String customerID, String eventID, String eventType, String serv);
  String getBookingSchedule (String customerID, String serv);
  String cancelEvent (String customerID, String eventID, String eventType, String serv);
  String swapEvent (String customerID, String newEventID, String newEventType, String oldEventID, String oldEventType, String serv);
  void shutdown ();
} // interface ManagerOperations
