package DEMSApp;


/**
* DEMSApp/Manager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CM.idl
* Sunday, March 1, 2020 8:09:59 AM EST
*/

public interface Manager extends ManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Manager
