package DEMSApp;

/**
* DEMSApp/ManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CM.idl
* Sunday, March 1, 2020 8:09:59 AM EST
*/

public final class ManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public DEMSApp.Manager value = null;

  public ManagerHolder ()
  {
  }

  public ManagerHolder (DEMSApp.Manager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DEMSApp.ManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DEMSApp.ManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DEMSApp.ManagerHelper.type ();
  }

}
